name: CAML
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - mlxtend
  - watermark
  - xgboost
  - optuna
  - hyperopt
  - imbalanced-learn
  